{{- $labels := include "cluster.labels" . }}
{{- $secrets := .Values.secrets }}
{{- $namespaces := append .Values.namespaces "default" | uniq }}
{{- range $secretName, $secretValue := $secrets }}
{{- range $namespace := (default $namespaces $secretValue.namespaces) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $namespace }}
  labels: {{ $labels | nindent 4 }}
type: {{ default "Opaque" $secretValue.type }}
data:
  {{- if (eq (toString $secretValue.type) "kubernetes.io/dockerconfigjson") -}}
    {{- printf ".dockerconfigjson: %s" (include "cluster.containerRegistrySecret" $secretValue.data) | trim | nindent 2 }}
  {{- else -}}
    {{- toYaml $secretValue.data | trim | nindent 2 }}
  {{- end }}

---
{{- end }}
{{- end }}
